### ISSUE TITLE
Missing area in 2 PC's connected to the same world

### ISSUE THREAD

**Issue by blizking** [exokitxr/zeo#162]
![screenshot 4](https://user-images.githubusercontent.com/26114104/30686432-e35444e4-9ed5-11e7-9394-80dff4e6f065.png)
![screenshot 69](https://user-images.githubusercontent.com/26114104/30686433-e3544f3e-9ed5-11e7-8570-5a7b5cefd968.png)
![screenshot 3 1](https://user-images.githubusercontent.com/26114104/30686469-ff75b842-9ed5-11e7-8ad7-18690690b993.png)

**Comment by avaer** [comment]
Thanks, I'll need to look into this again when redoing the `npc` mod.

Looks like missing chunks and then console errors from NPC's are trying to walk around on a heightfield that doesn't exist. ...Which makes sense since we got rid of heightfields in favor of true voxel potential fields for the terrain.

I'll kill the npc mod from defaults for now so it doesn't crash as bad, then put everything back when NPC behavior is ported to the voxel potential field.

**Comment by avaer** [comment]
Should be fixed with https://github.com/modulesio/zeo/commit/ede8e1401cab1a38915cd66a69521db07c901445.

@blizking Please let me know if you're still seeing this!
